#! /bin/bash
#
# installs a local mysql server and the native mysql ruby gem

# extract this dependency checking out into another script
# so i can merely say `check_dependencies ruby gem`

. ~/.bash_functions/dependency_checking
check_dependencies ruby gem

sudo aptitude install -y mysql-server-5.0 build-essential libmysqlclient15-dev
sudo gem install mysql
