source "http://rubygems.org"
gem "rspec", :require => "spec"
gem "clogger"
gem "git"
gem "hoe"
gem "jeweler"
gem "parseconfig"
gem "rcov"
gem "wirble"
gem "yard"
gem "hirb"
gem "homesick"
gem "nokogiri"
